import type { MenuCategory, MenuItem } from "@/types";

export const menuCategories: MenuCategory[] = [
  { id: "snacks", name: "Snacks", sort_order: 1, is_active: true },
  { id: "cold-tasting", name: "Cold Tasting", sort_order: 2, is_active: true },
  { id: "yakimono", name: "Yakimono", sort_order: 3, is_active: true },
  { id: "handroll-fin", name: "Handroll — Fin Fish", sort_order: 4, is_active: true },
  { id: "handroll-premium", name: "Handroll — Premium", sort_order: 5, is_active: true },
  { id: "handroll-plant", name: "Handroll — Plant-Based", sort_order: 6, is_active: true },
];

export const menuItems: MenuItem[] = [
  // ─── Snacks ───
  {
    id: "sn1",
    category_id: "snacks",
    name: "Miso Soup",
    description: "Green onion, tofu, shiitake, wakame.",
    price: 5,
    image_url: null,
    dietary_tags: ["V"],
    is_available: true,
    sort_order: 1,
  },
  {
    id: "sn2",
    category_id: "snacks",
    name: "Edamame",
    description: "Togarashi, sea salt.",
    price: 4,
    image_url: null,
    dietary_tags: ["VG", "GF", "DF"],
    is_available: true,
    sort_order: 2,
  },
  {
    id: "sn3",
    category_id: "snacks",
    name: "Chips & Dips",
    description: "Japanese potato chips, blue crab dip, smoked trout, chives.",
    price: 18,
    image_url: null,
    dietary_tags: [],
    is_available: true,
    sort_order: 3,
  },
  {
    id: "sn4",
    category_id: "snacks",
    name: "Seasonal Sunomono",
    description: "Strawberry, fennel, cured cucumber. Add crab +$6.",
    price: 10,
    image_url: null,
    dietary_tags: ["V", "GF"],
    is_available: true,
    sort_order: 4,
  },
  {
    id: "sn5",
    category_id: "snacks",
    name: "Uni Ham (1 pc)",
    description: "Sea urchin, country ham, black truffle.",
    price: 35,
    image_url: null,
    dietary_tags: [],
    is_available: true,
    sort_order: 5,
  },
  {
    id: "sn6",
    category_id: "snacks",
    name: "Mushroom Salad",
    description: "Trumpet, shiitake, red mizuna, sesame.",
    price: 9,
    image_url: null,
    dietary_tags: ["VG", "GF", "DF"],
    is_available: true,
    sort_order: 6,
  },
  {
    id: "sn7",
    category_id: "snacks",
    name: "Midori Salad",
    description: "Seasonal greens, green goddess, pickled onions, furikake.",
    price: 7,
    image_url: null,
    dietary_tags: ["VG"],
    is_available: true,
    sort_order: 7,
  },

  // ─── Cold Tasting ───
  {
    id: "ct1",
    category_id: "cold-tasting",
    name: "Hamachi Crudo",
    description: "Orange, ponzu, orange oil, serrano pepper.",
    price: 24,
    image_url: null,
    dietary_tags: ["GF", "DF"],
    is_available: true,
    sort_order: 1,
  },
  {
    id: "ct2",
    category_id: "cold-tasting",
    name: "Toro Cashew",
    description: "Sultana raisin, shiro dashi, negi, smoked oil.",
    price: 32,
    image_url: null,
    dietary_tags: ["NUTS"],
    is_available: true,
    sort_order: 2,
  },
  {
    id: "ct3",
    category_id: "cold-tasting",
    name: "Sake Crudo",
    description: "Ora King, ponzu, kale, blueberry, sunflower seed.",
    price: 20,
    image_url: null,
    dietary_tags: ["GF", "DF"],
    is_available: true,
    sort_order: 3,
  },
  {
    id: "ct4",
    category_id: "cold-tasting",
    name: "Tuna Sashimi",
    description: "Bluefin tuna, aged tamari, olive oil, chive.",
    price: 22,
    image_url: null,
    dietary_tags: ["GF", "DF"],
    is_available: true,
    sort_order: 4,
  },
  {
    id: "ct5",
    category_id: "cold-tasting",
    name: "Scallop Ceviche",
    description: "Brûléed grapefruit, tarragon, vanilla cinnamon aguachile.",
    price: 22,
    image_url: null,
    dietary_tags: ["GF", "DF"],
    is_available: true,
    sort_order: 5,
  },
  {
    id: "ct6",
    category_id: "cold-tasting",
    name: "Ora King Aburi",
    description: "Ora King salmon, sesame, ponzu, chive.",
    price: 24,
    image_url: null,
    dietary_tags: ["GF", "DF"],
    is_available: true,
    sort_order: 6,
  },
  {
    id: "ct7",
    category_id: "cold-tasting",
    name: "Wagyu A5 Carpaccio",
    description: "Farm egg, crispy mushrooms, wasabi, pickles, meyer lemon.",
    price: 29,
    image_url: null,
    dietary_tags: ["GF"],
    is_available: true,
    sort_order: 7,
  },

  // ─── Yakimono ───
  {
    id: "yk1",
    category_id: "yakimono",
    name: "Lobster Thermidor",
    description: "Blue crab, greens, chili crunch.",
    price: 29,
    image_url: null,
    dietary_tags: [],
    is_available: true,
    sort_order: 1,
  },
  {
    id: "yk2",
    category_id: "yakimono",
    name: "Salmon Butter",
    description: "Ora King salmon, smoked trout roe, sumac, tostada.",
    price: 24,
    image_url: null,
    dietary_tags: [],
    is_available: true,
    sort_order: 2,
  },
  {
    id: "yk3",
    category_id: "yakimono",
    name: "A5 Negimaki (4 pc)",
    description: "Flat iron, asian pear, leeks, tare.",
    price: 36,
    image_url: null,
    dietary_tags: ["GF"],
    is_available: true,
    sort_order: 3,
  },
  {
    id: "yk4",
    category_id: "yakimono",
    name: "Dry Aged Toro Steak",
    description: "Flat iron, asian pear, leeks, tare.",
    price: 65,
    image_url: null,
    dietary_tags: ["GF"],
    is_available: true,
    sort_order: 4,
  },
  {
    id: "yk5",
    category_id: "yakimono",
    name: "American Wagyu",
    description: "NY strip, sauce au poivre, green salad.",
    price: 42,
    image_url: null,
    dietary_tags: ["GF"],
    is_available: true,
    sort_order: 5,
  },

  // ─── Handroll — Fin Fish ───
  {
    id: "hf1",
    category_id: "handroll-fin",
    name: "Bluefin Tuna",
    description: "Cucumber, tamari.",
    price: 7,
    image_url: null,
    dietary_tags: ["GF", "DF"],
    is_available: true,
    sort_order: 1,
  },
  {
    id: "hf2",
    category_id: "handroll-fin",
    name: "Salmon",
    description: "Ora King salmon, cucumber, ponzu.",
    price: 6,
    image_url: null,
    dietary_tags: ["GF", "DF"],
    is_available: true,
    sort_order: 2,
  },
  {
    id: "hf3",
    category_id: "handroll-fin",
    name: "Hamachi",
    description: "Negi, smoked soy, cucumber.",
    price: 7,
    image_url: null,
    dietary_tags: ["GF", "DF"],
    is_available: true,
    sort_order: 3,
  },
  {
    id: "hf4",
    category_id: "handroll-fin",
    name: "Spicy Tuna",
    description: "Cucumber, avocado.",
    price: 9,
    image_url: null,
    dietary_tags: ["SPICY", "GF", "DF"],
    is_available: true,
    sort_order: 4,
  },

  // ─── Handroll — Premium ───
  {
    id: "hp1",
    category_id: "handroll-premium",
    name: "Fatty Tuna",
    description: "Negi, smoked soy, cucumber, kazami.",
    price: 9,
    image_url: null,
    dietary_tags: ["GF", "DF"],
    is_available: true,
    sort_order: 1,
  },
  {
    id: "hp2",
    category_id: "handroll-premium",
    name: "Maine Lobster",
    description: "Brown butter, tamari, negidare.",
    price: 12,
    image_url: null,
    dietary_tags: [],
    is_available: true,
    sort_order: 2,
  },
  {
    id: "hp3",
    category_id: "handroll-premium",
    name: "Scarlet Red Crab",
    description: "Avocado, cucumber, kewpie, chives.",
    price: 11,
    image_url: null,
    dietary_tags: [],
    is_available: true,
    sort_order: 3,
  },
  {
    id: "hp4",
    category_id: "handroll-premium",
    name: "Maine Scallop",
    description: "Avocado, cucumber, spicy mayo.",
    price: 11,
    image_url: null,
    dietary_tags: ["SPICY"],
    is_available: true,
    sort_order: 4,
  },
  {
    id: "hp5",
    category_id: "handroll-premium",
    name: "Uni",
    description: "Hand harvested in Maine.",
    price: 24,
    image_url: null,
    dietary_tags: ["GF", "DF"],
    is_available: true,
    sort_order: 5,
  },
  {
    id: "hp6",
    category_id: "handroll-premium",
    name: "Caviar",
    description: "Amber kaluga caviar, potato chip, chive.",
    price: 45,
    image_url: null,
    dietary_tags: ["GF"],
    is_available: true,
    sort_order: 6,
  },
  {
    id: "hp7",
    category_id: "handroll-premium",
    name: "Wagyu A5 Miyazaki Beef",
    description: "",
    price: 25,
    image_url: null,
    dietary_tags: ["GF"],
    is_available: true,
    sort_order: 7,
  },

  // ─── Handroll — Plant-Based ───
  {
    id: "hpb1",
    category_id: "handroll-plant",
    name: "Avocado",
    description: "Cucumber, yuzu koshō, furikake, tamari.",
    price: 5,
    image_url: null,
    dietary_tags: ["VG", "GF", "DF"],
    is_available: true,
    sort_order: 1,
  },
  {
    id: "hpb2",
    category_id: "handroll-plant",
    name: "Eggplant",
    description: "Sumiso, sesame seed.",
    price: 5,
    image_url: null,
    dietary_tags: ["VG", "GF", "DF"],
    is_available: true,
    sort_order: 2,
  },
  {
    id: "hpb3",
    category_id: "handroll-plant",
    name: "Mushroom",
    description: "Conserva, crispy mushroom, negidare.",
    price: 5,
    image_url: null,
    dietary_tags: ["VG", "GF", "DF"],
    is_available: true,
    sort_order: 3,
  },
  {
    id: "hpb4",
    category_id: "handroll-plant",
    name: "Cucumber",
    description: "Chili crunch.",
    price: 5,
    image_url: null,
    dietary_tags: ["VG", "GF", "DF"],
    is_available: true,
    sort_order: 4,
  },
];

export function getItemsByCategory(categoryId: string) {
  return menuItems.filter((item) => item.category_id === categoryId && item.is_available);
}
